コメント機能の課題を提出します！
ytakegawa/fjord-books_app pull request #6
Opened 2022-02-10 11:15 UTC by ytakegawa

よろしくお願いいたします。

2022-02-17 02:36 UTC, u1tnk requested changes

2022-02-17 02:36 UTC, u1tnk commented on app/controllers/comments_controller.rb
> +        format.html { redirect_to polymorphic_path(find_content(@comment)), notice: t('controllers.common.notice_create', name: Comment.model_name.human) }
polymophic_pathは redirect_toがやってくれるので明示的に書く必要は無いですよ。
`find_content(@comment)` だけで大丈夫です。

2022-02-17 02:36 UTC, u1tnk commented on app/controllers/comments_controller.rb
> +    respond_to do |format|
respond_toと `format.html`の指定も formatがhtmlしか無いなら書く必要無いですよ。

2022-02-17 02:36 UTC, u1tnk commented on app/controllers/comments_controller.rb
> +          @comments = @report.comments.order(:created_at).page(params[:page]).per(5)
この行は `find_content(@comment)` で取得したものをcotentとすると `content.comments.order(:created_at).page(params[:page]).per(5)` で共通化できます。

2022-02-17 02:36 UTC, u1tnk commented on app/controllers/comments_controller.rb
> +    @comment.destroy
destroyで validation errorになる事はほぼ無いですが、不具合によってなる事はあって、そのときにエラーを検知していないと原因が分からずハマるので、 `destroy!`を使うようにしましょう。不具合があるときは 例外になるので検知できます。

2022-02-18 08:40 UTC, ytakegawa commented on app/controllers/comments_controller.rb
> +        format.html { redirect_to polymorphic_path(find_content(@comment)), notice: t('controllers.common.notice_create', name: Comment.model_name.human) }
ご指摘ありがとうございます。
そうなのですね。勉強になりました。修正します。

2022-02-18 08:41 UTC, ytakegawa commented on app/controllers/comments_controller.rb
> +    respond_to do |format|
ご指摘ありがとうございます。
他の部分についても同様のコードがありましたので修正します。

2022-02-18 08:46 UTC, ytakegawa commented on app/controllers/comments_controller.rb
> +          @comments = @report.comments.order(:created_at).page(params[:page]).per(5)
仰る通り、`find_content(@comment)`を使うことでコードの重複がなくなりスッキリしました！
ありがとうございます。
また、`@cotent = find_content(@comment)`とすることで`@report = Report.find(params[:report_id])`と`@book = Book.find(params[:book_id])`も共通化することができそうなので、そのように修正します。

2022-02-18 08:49 UTC, ytakegawa commented on app/controllers/comments_controller.rb
> +    @comment.destroy
なるほどです。勉強になります。修正します

2022-02-20 07:41 UTC, u1tnk approved these changes

2022-02-22 07:52 UTC, merged